### ISSUE TITLE
Remove Lodash

### ISSUE THREAD

**Issue by GreenPioneer** [greenpioneersolutions/auto-parse#11]
Remove lodash because there's no need to be dependent on it

**Comment by GreenPioneer** [comment]
@IonicaBizau double check me on this commit and let me know if I missed anything in this [Commit](https://github.com/greenpioneersolutions/auto-parse/commit/2c1b15d81159bd8d3bfaad0aa24cf2d4444919ce)

**Comment by IonicaBizau** [comment]
@GreenPioneer Instead of doing `value.toString()` I'd do `String(value)` or `"" + value`, because just in case `value` is `null` or `undefined`, that would break the execution.

**Comment by GreenPioneer** [comment]
@IonicaBizau  I just did some simple tests and `null` & `undefined` didnt break anything. Im going to go with `String(value)`

**Comment by IonicaBizau** [comment]
@GreenPioneer Cool! Maybe there are additional checks there.
