### ISSUE TITLE
Date With Timezone Parse

### ISSUE THREAD

**Issue by HaolinWang8** [greenpioneersolutions/auto-parse#15]
How to set up timezone on autoParse for Date parsing.

autoParse("1/1/2019", Date);

For this kind of date type, how should I setup a time zone for parsing.

Thanks!!!

**Comment by GreenPioneer** [comment]
Idk how i wasn't ever alerted to this

to be honest i wouldnt mess with anything custom for timezones - i would use [https://momentjs.com/timezone/](https://momentjs.com/timezone/)
