### ISSUE TITLE
Does not work with query-string

### ISSUE THREAD

**Issue by dy** [greenpioneersolutions/auto-parse#16]
```js
import autoParse from 'auto-parse'
import qs from 'query-string'

// returns {}
autoParse(qs.parse('?order=asc&orderBy=1'))

// returns {order: 'asc', orderBy=1}
autoParse(Object.assign({}, qs.parse('?order=asc&orderBy=1')))
```

Not sure where does that belong, but it's not what it is expected to be.

@sindresorhus @GreenPioneer

**Comment by GreenPioneer** [comment]
@dy  Looking into it

**Comment by GreenPioneer** [comment]
found it [https://github.com/sindresorhus/query-string/blob/master/index.js#L205](https://github.com/sindresorhus/query-string/blob/master/index.js#L205)
They were treating it as a null object which has no properties

**Comment by GreenPioneer** [comment]
Fixed
