### ISSUE TITLE
Check if the types are the same

### ISSUE THREAD

**Issue by IonicaBizau** [greenpioneersolutions/auto-parse#9]
If the types are the same in `parseType`, we shouldn't convert anything.

## Expected Behavior
For instance, do not convert an existing array to another array.

## Current Behavior
`parseType([42], Array)` => `[[42]]`

## Possible Solution
Will open a PR.

## Steps to Reproduce (for bugs)
`parseType([42], Array)` => `[[42]]`

## Context
https://github.com/IonicaBizau/tilda

**Comment by GreenPioneer** [comment]
Im going to consider this an enhancement and not a bug @IonicaBizau

**Comment by IonicaBizau** [comment]
@GreenPioneer Yes, makes sense.
